### ISSUE TITLE
How to use ImageNet pretrain in your code?

### ISSUE THREAD

**Issue by John1231983** [yeephycho/densenet-tensorflow#2]
Hello, I have achieved very good performance in my dataset using your code. Right now, I want to use ImageNet pretrain model to improve performance more. Could you tell me how can I use it based on your code? I have convert imagenet pretrain model based on caffe model at https://github.com/shicai/DenseNet-Caffe

You can download my convert pretrain model at https://drive.google.com/open?id=1nby_ZC7ELkqaVaipPc8eKrzoHb05BGx4

**Comment by yeephycho** [comment]
Hi there,
Since this implementation is a standalone implementation. The architecture is different from the literature, for example there's only 54 conv. layer instead of the 121 from the original paper.
So, there's no perfect way to convert a pre-trained model to this implementation.

However, I recommend you to star or fork another repo. of mine named [nasnet-tensorflow](https://github.com/yeephycho/nasnet-tensorflow) .
Nasnet is the best architecture so far from my personal view, and thanks to google, there's pre-trained models on imagenet, I well documented that repo. and you can find it's much more easier to use than densenet.

I will no longer maintain this repo., so good luck~

Yours Yeephycho
